name: Angrylane
favicon: null
layout_spectrum: 0.56154
typography_spectrum: 0.85266
title: Angry Lane
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#2e2e30'
    - '#b8b7bc'
    - '#fafafa'
    - '#69696b'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
