name: Angrylane
favicon: null
layout_spectrum: 0.3842
typography_spectrum: 0.67022
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#101010'
    - '#40403e'
    - '#92918d'
    - '#c8b7a7'
    - '#fefcfd'
  brandStrength: 0.7415617823135108
  lightness: 0.47373152058571577
  saturation: 0.5625
  rhythmicContrast: 0.7959652508143336
purpose: []
