name: Angrylane
favicon: null
layout_spectrum: 0
typography_spectrum: 0.85266
title: Angry Lane
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0a'
    - '#fefefe'
    - '#60564d'
    - '#d4cbbb'
    - '#bdaf95'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
