typography_spectrum: 0.85266
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#48474c'
    - '#959597'
    - '#c3c3c5'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.11867
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/513f9411-1760-447e-baed-f3c81051bae0.png
name: Angry Lane
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    url: 'http://www.angrylane.com/pages/about-us'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1147e5b1-095c-440b-9357-342e8a863e5a.ico
title: Luxury Quality Essentials
description: Luxury Quality Essentials
purpose: []
