typography_spectrum: 0.32468194561079144
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.9600013780873269
  lightness: 0.73525499436073
  saturation: 0.7269598683342338
  rhythmicContrast: 0.27716875402256846
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.1543160998262465
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/513f9411-1760-447e-baed-f3c81051bae0.png
name: Angry Lane
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    url: 'http://www.angrylane.com/pages/about-us'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1147e5b1-095c-440b-9357-342e8a863e5a.ico
title: Luxury Quality Essentials
description: Luxury Quality Essentials
purpose: []
