typography_spectrum: 0.85266
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#48474c'
    - '#959597'
    - '#c3c3c5'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.75
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.11867
analytics:
  google: null
  facebook: null
  twitter: null
name: ANGRY LANE
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    url: 'http://www.angrylane.com/pages/about-us'
    type: external
favicon: null
title: Angry Lane
description: Timeless Essentials
purpose: []
