typography_spectrum: 0.44362225919030607
color:
  brandColors:
    - '#FFFEFF'
    - '#03040D'
    - '#AAABC4'
    - '#777A90'
    - '#555355'
  brandStrength: 0.5387167616281658
  lightness: 0.09124860819429159
  saturation: 0.34169258642941713
  rhythmicContrast: 0.6969551078509539
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.33518604235723615
analytics:
  google: null
  facebook: null
  twitter: null
name: ANGRY LANE
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    url: 'http://www.angrylane.com/pages/about-us'
    type: external
favicon: null
title: Angry Lane
description: Luxury Quality Essentials
purpose: []
